# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user_service.proto

require 'google/protobuf'

descriptor_data = "\n\x12user_service.proto\x12\x0fsimple_web_rpc\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"I\n\x0fGetUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05email\x18\x03 \x01(\t\x12\r\n\x05found\x18\x04 \x01(\x082P\n\x0bUserService\x12A\n\x07GetUser\x12\x1f.simple_web_rpc.GetUserRequest\x1a .simple_web_rpc.GetUserResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module SimpleWebRpc
  GetUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('simple_web_rpc.GetUserRequest').msgclass
  GetUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('simple_web_rpc.GetUserResponse').msgclass
end
