# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user_service.proto for package 'user'

require 'grpc'
require_relative 'user_service_pb'

module GrpcUser
  module UserService
    # gRPC service implementation for user operations
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'user.UserService'

      rpc :GetUser, ::GrpcUser::GetUserRequest, ::GrpcUser::GetUserResponse
    end

    Stub = Service.rpc_stub_class
  end
end
