# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user_service.proto for package 'simple_web_rpc'

require 'grpc'
require_relative 'user_service_pb'

module SimpleWebRpc
  module UserService
    # gRPC service implementation for user operations
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'simple_web_rpc.UserService'

      rpc :GetUser, ::SimpleWebRpc::GetUserRequest, ::SimpleWebRpc::GetUserResponse
    end

    Stub = Service.rpc_stub_class
  end
end
