# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: simpleweb.proto for package 'simpleweb'

require 'grpc'
require 'simpleweb_pb'

module Simpleweb
  module WorkerService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'simpleweb.WorkerService'

      rpc :ProcessJob, ::Simpleweb::JobRequest, ::Simpleweb::JobReply
    end

    Stub = Service.rpc_stub_class
  end
end
