# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simpleweb.proto

require 'google/protobuf'

# rubocop:disable Layout/LineLength
descriptor_data = "\n\x0fsimpleweb.proto\x12\tsimpleweb\".\n\nJobRequest\x12\x10\n\x08job_name\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\x05\",\n\x08JobReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32K\n\rWorkerService\x12:\n\nProcessJob\x12\x15.simpleweb.JobRequest\x1a\x13.simpleweb.JobReply\"\x00\x62\x06proto3"
# rubocop:enable Layout/LineLength

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Simpleweb
  JobRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('simpleweb.JobRequest').msgclass
  JobReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('simpleweb.JobReply').msgclass
end
