name: "Rubocop"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Ruby
      uses: ruby/setup-ruby@0481980f17b760ef6bca5e8c55809102a0af1e5a 
      with:
        ruby-version: '3.2.0'
        bundler-cache: true

    - uses: reviewdog/action-rubocop@b6d5e953a5fc0bf3ab65254e77730ea2174d6d6d 
      with:
        reporter: github-pr-review 
        skip_install: true
        use_bundler: true